# Project information
site_name: ACI 4 Lab Guide
site_description: ACI Version 4 Lab Guide
site_author: Claudia de Luna
site_url: https://github.com/cldeluna/aci4_labguide.git

# Repository
repo_name: cldeluna/aci4_labguide
repo_url: https://github.com/cldeluna/aci4_labguide.git

# Copyright
copyright: Copyright &copy; 2016 - 2020

# Configuration
theme:
  name: material
  language: en
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono

# Extras
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/squidfunk
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/squidfunk
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/squidfunk

# Google Analytics
google_analytics:
  - UA-XXXXXXXX-X
  - auto

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
