# Project information
site_name: ACI 4 Lab Guide
site_description: ACI Version 4 Lab Guide
site_author: Claudia de Luna
site_url: https://github.com/cldeluna/aci4_labguide.git

# Repository
repo_name: cldeluna/aci4_labguide
repo_url: https://github.com/cldeluna/aci4_labguide.git

# Copyright
copyright: Copyright &copy; 2016 - 2020

# Configuration
theme:
  name: material
  language: en
  palette:
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono

# Extras
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/squidfunk
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/squidfunk
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/squidfunk

# Google Analytics
google_analytics:
  - UA-XXXXXXXX-X
  - auto

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true


# Navigation
nav:
  - Home: index.md
  - Topology & Design: topology.md
  - Getting Around: lab_tips.md
  - Step 1 - Fabric Discovery : 1_Fabric_Discovery/overview.md
  - Step 2 - Fabric & Access Policies: 2_Fabric_Access_Policies/overview.md
  - Step 3 - Tenants: 3_Tenants/overview.md
  - Step 4 - Host & Layer 2 Connectivity: 4_Host_L2_Connectivity/overview.md
  - Step 5 - External Layer 3 Connectivity: 5_External_L3_Connectivity/overview.md
  - Step 6 - Management & Operations: 6_Management_Operations/overview.md
  - Step 7 - Advanced Topics: 7_Advanced_Topics/overview.md
  - Step 8 - Troubleshooting: 8_Troubleshooting/overview.md
  - Step 9 - Programmability: 9_Programmability/overview.md